import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Hydrate from "./components/Hydrate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //Fetching the user
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className="mx-60">
        <Hydrate>
          <NavBar user={session?.user} expires={session?.expires || ""} />
          {children}
        </Hydrate>
      </body>
    </html>
  );
}
